routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AjaxController;
use App\Http\Controllers\Dashboard\RoleController;
use App\Http\Controllers\Dashboard\UserController;
use App\Http\Controllers\Dashboard\TugboatController;
use App\Http\Controllers\Dashboard\UserLogController;
use App\Http\Controllers\Dashboard\TongkangController;
use App\Http\Controllers\Dashboard\DashboardController;
use App\Http\Controllers\Dashboard\JettyController;
use App\Http\Controllers\Dashboard\PermissionController;
use App\Http\Controllers\Perusahaan\PerusahaanController;

Auth::routes();

Route::group(["middleware" => ["auth","dashboard"]], function ()
{
    Route::get('/', [DashboardController::class, "index"])->name("dashboard.index");

    // DATATABLES
        Route::get('permission/data', [PermissionController::class, 'data'])->name('permission.data');
        Route::get('user/data', [UserController::class, 'data'])->name('user.data');
        Route::get('user-log/data', [UserLogController::class, 'data'])->name('user-log.data');
        Route::get('tugboat/data', [TugboatController::class, 'data'])->name('tugboat.data');
        Route::get('tongkang/data', [TongkangController::class, 'data'])->name('tongkang.data');
        Route::get('jetty/data', [JettyController::class, 'data'])->name('jetty.data');
    // 

    // AUTH
        Route::resource("user", UserController::class);
        Route::get("notifikasi", [UserController::class, "notifikasiIndex"])->name("notifikasi.index");
        
        Route::resource("role", RoleController::class);
        Route::get("role-add-user/{roleId}", [RoleController::class, "addUserIndex"])->name("role.add-user.index");
        Route::put("role-add-user/{roleId}", [RoleController::class, "addUserStore"])->name("role.add-user.store");
        Route::resource("permission", PermissionController::class);
        Route::resource("user-log", UserLogController::class);
        Route::post("user-log-upload/{userLogId}", [UserLogController::class, "userLogUpload"])->name("user-log.upload");
    // 

    // TUGBOAT
        Route::resource("tugboat", TugboatController::class);
        Route::post("tugboat-upload/{tugboatId}", [TugboatController::class, "upload"])->name("tugboat.upload");
        Route::get("tugboat-remove-file/{tugboatId}/{field}", [TugboatController::class, "removeFile"])->name("tugboat.remove-file");
        Route::post("tugboat-nahkoda/{tugboatId}", [TugboatController::class, "nahkodaStore"])->name("tugboat.nahkoda.store");
        Route::delete("tugboat-nahkoda/{nahkodaId}", [TugboatController::class, "nahkodaDelete"])->name("tugboat.nahkoda.delete");
    // 

    // TONGKANG
        Route::resource("tongkang", TongkangController::class);
        Route::post("tongkang-upload/{tongkangId}", [TongkangController::class, "upload"])->name("tongkang.upload");
        Route::get("tongkang-remove-file/{tongkangId}/{field}", [TongkangController::class, "removeFile"])->name("tongkang.remove-file");
    // 

    // JETTY
        Route::resource("jetty", JettyController::class);
        Route::post("jetty-upload/{jettyId}", [JettyController::class, "upload"])->name("jetty.upload");
        Route::get("jetty-remove-file/{jettyId}/{field}", [JettyController::class, "removeFile"])->name("jetty.remove-file");
    // 
    
    // PROFILE
        Route::get("profile", [UserController::class, "editProfile"])->name("profile.edit");
        Route::post("profile", [UserController::class, "updateProfile"])->name("profile.update");
    // 

    // AJAX
        Route::group(["prefix" => "ajax/", "as" => "ajax."], function ()
        {
            Route::get("mark-all-as-read", [AjaxController::class, "markAllAsRead"])->name("mark-all-as-read");
            Route::get("get-kabupaten", [AjaxController::class, "getKabupaten"])->name("get-kabupaten");
            Route::get("get-kecamatan", [AjaxController::class, "getKecamatan"])->name("get-kecamatan");
            Route::get("get-kelurahan", [AjaxController::class, "getKelurahan"])->name("get-kelurahan");
        });
    // 

    // PERUSAHAAN
        Route::group(["prefix" => "user-perusahaan/", "as" => "user-perusahaan."], function ()
        {
            Route::get("perusahaan", [PerusahaanController::class, "index"])->name("perusahaan.index");
            Route::post("perusahaan", [PerusahaanController::class, "store"])->name("perusahaan.store");
            Route::post("perusahaan-upload/{perusahaanId}", [PerusahaanController::class, "upload"])->name("perusahaan.upload");
            Route::get("perusahaan-remove-file/{perusahaanId}/{field}", [PerusahaanController::class, "removeFile"])->name("perusahaan.remove-file");
        });
    // 
});

app/Models/Tugboat.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Tugboat extends Model
{
    use HasFactory, SoftDeletes;

    protected $table = "tugboat";
    protected $fillable = [
        "nama_pemilik",
        "nib",
        "nama",
        "ukuran",
        "tonase_kotor",
        "registrasi_pas",
        "masa_berlaku_skksd",
        "surat_ukur_berlaku",
        "tanggal_pas",
        "masa_berlaku_izin_operasi",
        "masa_berlaku_izin_trayek",
        "jenis_kapal",
        "skksd_file",
        "surat_ukur_file",
        "pas_file",
        "izin_operasi_file",
        "izin_trayek_file",
        "nib_file",
        "perusahaan_id",
    ];

    // const
    const JENIS_KAPAL_KAPAL_BARANG                  = 1;
    const JENIS_KAPAL_KAPAL_PENUMPANG               = 2;
    const JENIS_KAPAL_KAPAL_BARANG_PENUMPANG        = 3;
    // 

    // data
    public  static function listJenisKapal()
    {
        return [
            self::JENIS_KAPAL_KAPAL_BARANG             => "Kapal Barang",
            self::JENIS_KAPAL_KAPAL_PENUMPANG          => "Kapal Penumpang",
            self::JENIS_KAPAL_KAPAL_BARANG_PENUMPANG   => "Kapal Barang & Penumpang",
        ];
    }

    public  static function listFiles()
    {
        return [
            [
                "name"                  => "skksd_file",
                "label"                 => "SKKSD",
            ],
            [
                "name"                  => "surat_ukur_file",
                "label"                 => "Surat Ukur",
            ],
            [
                "name"                  => "pas_file",
                "label"                 => "PAS Sungai Danau & Endorse",
            ],
            [
                "name"                  => "izin_operasi_file",
                "label"                 => "Izin Operasi",
            ],
            [
                "name"                  => "izin_trayek_file",
                "label"                 => "Izin Trayek",
            ],
            [
                "name"                  => "nib_file",
                "label"                 => "NIB",
            ],
        ];
    }
    // 

    // relations
    public function perusahaan()
    {
        return $this->belongsTo(Perusahaan::class, "perusahaan_id");
    }

    public function nahkoda()
    {
        return $this->hasMany(Nahkoda::class);
    }
    // 

    // attributes
    public function getJenisKapalStrAttribute()
    {
        return self::listJenisKapal()[$this->jenis_kapal] ?? "-";
    }

    public function getJenisKapalFormattedAttribute()
    {
        return labelHelper($this->jenis_kapal_str, "badge bg-primary");
    }

    public function getMasaBerlakuSkksdFormattedAttribute()
    {
        return formatDate("Y-m-d", "d-m-Y", $this->masa_berlaku_skksd);
    }

    public function getSuratUkurBerlakuFormattedAttribute()
    {
        return formatDate("Y-m-d", "d-m-Y", $this->surat_ukur_berlaku);
    }

    public function getTanggalPasFormattedAttribute()
    {
        return formatDate("Y-m-d", "d-m-Y", $this->tanggal_pas);
    }

    public function getMasaBerlakuIzinOperasiFormattedAttribute()
    {
        return formatDate("Y-m-d", "d-m-Y", $this->masa_berlaku_izin_operasi);
    }

    public function getMasaBerlakuIzinTrayekFormattedAttribute()
    {
        return formatDate("Y-m-d", "d-m-Y", $this->masa_berlaku_izin_trayek);
    }

    public function setMasaBerlakuSkksdAttribute($val)
    {
        $this->attributes["masa_berlaku_skksd"]     = formatDate("d-m-Y", "Y-m-d", $val);
    }

    public function setSuratUkurBerlakuAttribute($val)
    {
        $this->attributes["surat_ukur_berlaku"]     = formatDate("d-m-Y", "Y-m-d", $val);
    }

    public function setTanggalPasAttribute($val)
    {
        $this->attributes["tanggal_pas"]     = formatDate("d-m-Y", "Y-m-d", $val);
    }

    public function setMasaBerlakuIzinOperasiAttribute($val)
    {
        $this->attributes["masa_berlaku_izin_operasi"]     = formatDate("d-m-Y", "Y-m-d", $val);
    }

    public function setMasaBerlakuIzinTrayekAttribute($val)
    {
        $this->attributes["masa_berlaku_izin_trayek"]     = formatDate("d-m-Y", "Y-m-d", $val);
    }

    public function getSkksdFileStorageAttribute()
    {
        $str       = asset('assets/dashboard/images/noimage.png');

        if (!empty($this->skksd_file)) {
            $str   = Storage::url("tugboat_skksd_file/" . $this->skksd_file);
        }

        return $str;
    }

    public function getSuratUkurFileStorageAttribute()
    {
        $str       = asset('assets/dashboard/images/noimage.png');

        if (!empty($this->surat_ukur_file)) {
            $str   = Storage::url("tugboat_surat_ukur_file/" . $this->surat_ukur_file);
        }

        return $str;
    }

    public function getPasFileStorageAttribute()
    {
        $str       = asset('assets/dashboard/images/noimage.png');

        if (!empty($this->pas_file)) {
            $str   = Storage::url("tugboat_pas_file/" . $this->pas_file);
        }

        return $str;
    }

    public function getIzinOperasiFileStorageAttribute()
    {
        $str       = asset('assets/dashboard/images/noimage.png');

        if (!empty($this->izin_operasi_file)) {
            $str   = Storage::url("tugboat_izin_operasi_file/" . $this->izin_operasi_file);
        }

        return $str;
    }

    public function getIzinTrayekFileStorageAttribute()
    {
        $str       = asset('assets/dashboard/images/noimage.png');

        if (!empty($this->izin_trayek_file)) {
            $str   = Storage::url("tugboat_izin_trayek_file/" . $this->izin_trayek_file);
        }

        return $str;
    }

    public function getNibFileStorageAttribute()
    {
        $str       = asset('assets/dashboard/images/noimage.png');

        if (!empty($this->nib_file)) {
            $str   = Storage::url("tugboat_nib_file/" . $this->nib_file);
        }

        return $str;
    }
    // 

    // scopes
    public function scopeFilter($query, $request)
    {
        if (auth()->user()->roles->first()->name == "perusahaan") {
            empty(auth()->user()->perusahaan) ? $query->whereNull("id") : $query->where("perusahaan_id", auth()->user()->perusahaan->id);
        }

        return $query;
    }
    // 
}

app/Http/Controllers/Dashboard/TugboatController.php
<?php

namespace App\Http\Controllers\Dashboard;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Http\Controllers\Controller;
use App\Http\Requests\TugboatRequest;
use App\Repositories\Dashboard\TugboatRepository;

class TugboatController extends Controller
{
    protected $repository;

    public function __construct(TugboatRepository $repository)
    {
        $this->title            = 'Tugboat';
        $this->viewPath         = 'dashboard.pages.';
        $this->repository       = $repository;
        $this->modelRequest     = TugboatRequest::class;
    }

    public function upload(Request $request, $id)
    {
        try {
            
            DB::beginTransaction();

            $items      = $this->repository->upload(request()->all(), $id);

            DB::commit();

            return response()->json(makeResponse(true, 'success', [
                "view"          => view("components.files.after_upload", $items)->render(),
                "parent_div"    => request()->field,
            ]));

        } catch (\Throwable $th) {
            DB::rollback();

            throw $th;
        }
    }

    public function removeFile(Request $request, $id, $jenisFile)
    {
        try {
            
            DB::beginTransaction();

            $this->repository->removeFile(request()->all(), $id, $jenisFile);

            DB::commit();

            return redirect()->back()->withSuccess("Berhasil menghapus file");

        } catch (\Throwable $th) {
            DB::rollback();

            throw $th;
        }
    }

    public function nahkodaStore(Request $request, $tugboatId)
    {
        try {
            
            DB::beginTransaction();

            $this->repository->nahkodaStore(request()->all(), $tugboatId);

            DB::commit();

            return redirect()->back()->withSuccess("Berhasil menambahkan data Nahkoda");

        } catch (\Throwable $th) {
            DB::rollback();

            throw $th;
        }
    }

    public function nahkodaDelete($nahkodaId)
    {
        try {
            
            DB::beginTransaction();

            $this->repository->nahkodaDelete($nahkodaId);

            DB::commit();

            return redirect()->back()->withSuccess("Berhasil menghapus data Nahkoda");

        } catch (\Throwable $th) {
            DB::rollback();

            throw $th;
        }
    }
}

resources/views/dashboard/pages/tugboat/button.blade.php
<div class="btn-group">
    <button class="btn btn-primary btn-sm dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
        Options
    </button>
    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
        <a class="dropdown-item" href="{{ route($routes['show'], $model->id) }}">Detail</a>
        <a class="dropdown-item" href="{{ route($routes['edit'], $model->id) }}">Edit</a>
        {!! Form::open(['route' => [$routes['destroy'], $model->id], 'method' => 'DELETE', 'class' => 'delete','style' => 'display: contents']) !!}
            <a class="dropdown-item" href="#" onclick="SwalDelete($(this).closest('form'))">Delete</a>
        {!! Form::close() !!}
    </div>
</div>

resources/views/dashboard/pages/tugboat/create.blade.php
@extends('dashboard.layouts.app')

@push('dashboard.css')
    
@endpush


@section('dashboard.content')
    <div class="content-body">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header border-bottom">
                        <h4 class="card-title">{{ $sub_title }}</h4>
                    </div>
                    <div class="card-body mt-2">
                        {!! Form::open(['route' => $routes['store'], 'method' => 'POST','class' => 'form form-horizontal','enctype' => 'multipart/form-data']) !!}
                        
                            @include($form)
                            
                            <div class="row">
                                <div class="col-sm-9 offset-sm-3">
                                    <button type="submit" class="btn btn-primary me-1">Submit</button>
                                </div>
                            </div>
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('dashboard.js')
    
@endpush

resources/views/dashboard/pages/tugboat/edit.blade.php
@extends('dashboard.layouts.app')

@push('dashboard.css')
    
@endpush


@section('dashboard.content')
    <div class="content-body">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header border-bottom">
                        <h4 class="card-title">{{ $sub_title }}</h4>
                    </div>
                    <div class="card-body mt-2">
                        {!! Form::model($item,['route' => [$routes['update'],$item->id], 'method' => 'PUT', 'class' => 'form form-horizontal','enctype' => 'multipart/form-data']) !!}
                            
                            @include($form)
                            
                            <div class="row">
                                <div class="col-sm-9 offset-sm-3">
                                    <button type="submit" class="btn btn-primary me-1">Submit</button>
                                </div>
                            </div>
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('dashboard.js')
    
@endpush

resources/views/dashboard/pages/tugboat/form.blade.php
<div class="row">
    <div class="col-12">
        <div class="mb-1 row">
            <div class="col-sm-3">
                <label class="col-form-label">Nama Pemilik</label>
            </div>
            <div class="col-sm-9">
                {!! Form::text('nama_pemilik', null, ['class' => 'form-control', 'placeholder' => 'Nama Pemilik']) !!}
            </div>
        </div>
    </div>
    <div class="col-12">
        <div class="mb-1 row">
            <div class="col-sm-3">
                <label class="col-form-label">NIB</label>
            </div>
            <div class="col-sm-9">
                {!! Form::text('nib', null, ['class' => 'form-control', 'placeholder' => 'NIB']) !!}
            </div>
        </div>
    </div>
    <div class="col-12">
        <div class="mb-1 row">
            <div class="col-sm-3">
                <label class="col-form-label">Nama Tugboat</label>
            </div>
            <div class="col-sm-9">
                {!! Form::text('nama', null, ['class' => 'form-control', 'placeholder' => 'Nama Tugboat']) !!}
            </div>
        </div>
    </div>
    <div class="col-12">
        <div class="mb-1 row">
            <div class="col-sm-3">
                <label class="col-form-label">Ukuran (PxLxD)</label>
            </div>
            <div class="col-sm-9">
                {!! Form::text('ukuran', null, ['class' => 'form-control', 'placeholder' => 'Ukuran (PxLxD)']) !!}
            </div>
        </div>
    </div>
    <div class="col-12">
        <div class="mb-1 row">
            <div class="col-sm-3">
                <label class="col-form-label">Tonase Kotor (GT)</label>
            </div>
            <div class="col-sm-9">
                {!! Form::number('tonase_kotor', null, ['class' => 'form-control', 'placeholder' => 'Tonase Kotor (GT)']) !!}
            </div>
        </div>
    </div>
    <div class="col-12">
        <div class="mb-1 row">
            <div class="col-sm-3">
                <label class="col-form-label">Registrasi PAS / Tanda PAS</label>
            </div>
            <div class="col-sm-9">
                {!! Form::text('registrasi_pas', null, ['class' => 'form-control', 'placeholder' => 'Registrasi PAS / Tanda PAS']) !!}
            </div>
        </div>
    </div>
    <div class="col-12">
        <div class="mb-1 row">
            <div class="col-sm-3">
                <label class="col-form-label">Masa Berlaku SKKSD (s/d Expired Dicekal)</label>
            </div>
            <div class="col-sm-9">
                {!! Form::text('masa_berlaku_skksd', isset($item) ? $item->masa_berlaku_skksd_formatted : null, ['class' => 'form-control flatpicker', 'placeholder' => 'Masa Berlaku SKKSD (s/d Expired Dicekal)']) !!}
            </div>
        </div>
    </div>
    <div class="col-12">
        <div class="mb-1 row">
            <div class="col-sm-3">
                <label class="col-form-label">Surat Ukur Masa Berlaku s/d</label>
            </div>
            <div class="col-sm-9">
                {!! Form::text('surat_ukur_berlaku', isset($item) ? $item->surat_ukur_berlaku_formatted : null, ['class' => 'form-control flatpicker', 'placeholder' => 'Surat Ukur Masa Berlaku s/d']) !!}
            </div>
        </div>
    </div>
    <div class="col-12">
        <div class="mb-1 row">
            <div class="col-sm-3">
                <label class="col-form-label">Tanggal PAS Sungai Danau & Endorse</label>
            </div>
            <div class="col-sm-9">
                {!! Form::text('tanggal_pas', isset($item) ? $item->tanggal_pas_formatted : null, ['class' => 'form-control flatpicker', 'placeholder' => 'Tanggal PAS Sungai Danau & Endorse']) !!}
            </div>
        </div>
    </div>
    <div class="col-12">
        <div class="mb-1 row">
            <div class="col-sm-3">
                <label class="col-form-label">Masa Berlaku Izin Operasi</label>
            </div>
            <div class="col-sm-9">
                {!! Form::text('masa_berlaku_izin_operasi', isset($item) ? $item->masa_berlaku_izin_operasi_formatted : null, ['class' => 'form-control flatpicker', 'placeholder' => 'Masa Berlaku Izin Operasi']) !!}
            </div>
        </div>
    </div>
    <div class="col-12">
        <div class="mb-1 row">
            <div class="col-sm-3">
                <label class="col-form-label">Masa Berlaku Izin Trayek</label>
            </div>
            <div class="col-sm-9">
                {!! Form::text('masa_berlaku_izin_trayek', isset($item) ? $item->masa_berlaku_izin_trayek_formatted : null, ['class' => 'form-control flatpicker', 'placeholder' => 'Masa Berlaku Izin Trayek']) !!}
            </div>
        </div>
    </div>
    <div class="col-12">
        <div class="mb-1 row">
            <div class="col-sm-3">
                <label class="col-form-label">Jenis Kapal</label>
            </div>
            <div class="col-sm-9">
                {!! Form::select('jenis_kapal', $items["list_jenis_kapal"], null, ['class' => 'form-control select2', 'placeholder' => 'Pilih Jenis Kapal']) !!}
            </div>
        </div>
    </div>
</div>

resources/views/dashboard/pages/tugboat/index.blade.php
@extends('dashboard.layouts.app')

@push('dashboard.css')
    
@endpush


@section('dashboard.content')
    <div class="content-body">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header border-bottom">
                        <h4 class="card-title">{{ $sub_title }}</h4>
                        <a href="{{ route($routes['create']) }}" class="btn btn-primary">
                            <i data-feather="plus"></i> Add
                        </a>
                    </div>
                    <div class="card-datatable pb-2">
                        <table class="dt-general table">
                            <thead>
                                <tr>
                                    <th width="2%">#</th>
                                    <th>Nama</th>
                                    <th>Perusahaan</th>
                                    <th>Pemilik</th>
                                    <th>Jenis Kapal</th>
                                    <th class="text-center" width="2%">Options</th>
                                </tr>
                            </thead>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('dashboard.js')
    <script>
        const datatableUrl       = InitDatatable("{{ route($routes['data']) }}", 
                                                  ["nama", "nama_perusahaan", "nama_pemilik","jenis_kapal_formatted","options"],
                                                  []);
    </script>
@endpush

resources/views/dashboard/pages/tugboat/show.blade.php
@extends('dashboard.layouts.app')

@push('dashboard.css')
    <style>
    </style>    
@endpush

@section('dashboard.content')
    <div class="content-header row">
        <div class="content-header-left col-md-9 col-12 mb-2">
            <div class="row breadcrumbs-top">
                <div class="col-12">
                    <h2 class="content-header-title float-start mb-0">{{ $sub_title }}</h2>
                    <h2 class="float-start mb-0">&nbsp; {{ $item->nama }} ({{ $item->perusahaan->nama_perusahaan }})</h2>
                </div>
            </div>
        </div>
        <div class="content-header-right text-md-end col-md-3 col-12 d-md-block d-none">
            <div class="mb-1 breadcrumb-right">
                <div class="btn-group" role="group" aria-label="">
                    <div class="dropdown">
                        
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="content-body">
        <div class="row">
            <div class="col-xl-3 col-lg-3 col-md-5 order-1 order-md-0 sidebar-pmb-application">
                <div class="card">
                    <div class="card-body">
                        <div class="user-avatar-section mb-2">
                            <div class="d-flex align-items-center flex-column">
                                <div class="mb-1 mt-1">
                                    <i class="fa fa-ship" style="font-size: 100px;"></i>
                                </div>
                                <div class="user-info text-center">
                                    <h4>{{ $item->nama }}</h4>
                                    <span class="badge bg-light-secondary">{{ $item->perusahaan->nama_perusahaan ?? "-" }}</span>
                                </div>
                            </div>
                        </div>
                        <div class="info-container">
                            <div class="sidebar-menu-list ps ps--active-y">
                                <div class="list-group list-group-messages">
                                    <div class="fw-bolder mt-1">Nama Pemilik</div>
                                    <div class="text-gray-600">{{ $item->nama_pemilik ?? "-" }}</div>
                                    <div class="fw-bolder mt-1">NIB</div>
                                    <div class="text-gray-600">{{ $item->nib ?? "-" }}</div>
                                    <div class="fw-bolder mt-1">Ukuran PxLxD</div>
                                    <div class="text-gray-600">{{ $item->ukuran ?? "-" }}</div>
                                    <div class="fw-bolder mt-1">Tonase Kotor (GT)</div>
                                    <div class="text-gray-600">{{ $item->tonase_kotor }}</div>
                                    <div class="fw-bolder mt-1">Registrasi PAS / Tanda PAS</div>
                                    <div class="text-gray-600">{{ $item->registrasi_pas }}</div>
                                    <div class="fw-bolder mt-1">Masa Berlaku SKKSD</div>
                                    <div class="text-gray-600">{{ $item->masa_berlaku_skksd_formatted }}</div>
                                    <div class="fw-bolder mt-1">Masa Berlaku Surat Ukur</div>
                                    <div class="text-gray-600">{{ $item->surat_ukur_berlaku_formatted }}</div>
                                    <div class="fw-bolder mt-1">Tanggal PAS Sungai Danau & Endorse</div>
                                    <div class="text-gray-600">{{ $item->tanggal_pas_formatted }}</div>
                                    <div class="fw-bolder mt-1">Masa Berlaku Izin Operasi</div>
                                    <div class="text-gray-600">{{ $item->masa_berlaku_izin_operasi_formatted }}</div>
                                    <div class="fw-bolder mt-1">Masa Berlaku Izin Trayek</div>
                                    <div class="text-gray-600">{{ $item->masa_berlaku_izin_trayek_formatted }}</div>
                                </div>
                                <div class="ps__rail-x" style="left: 0px; bottom: 0px;">
                                    <div class="ps__thumb-x" tabindex="0" style="left: 0px; width: 0px;"></div>
                                </div>
                                <div class="ps__rail-y" style="top: 0px; right: 0px;">
                                    <div class="ps__thumb-y" tabindex="0" style="top: 0px; height: 0px;"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            
            <div class="col-xl-9 col-lg-9 col-md-7 order-0 order-md-1">
                <div class="row">
                    <div class="col-md-12">
                        <ul class="nav nav-pills mb-2">
                            <li class="nav-item">
                                <a class="nav-link active" id="file-attachment-tab" data-bs-toggle="tab" href="#file-attachment" aria-controls="file-attachment" role="tab" aria-selected="true">
                                    <i class="fa fa-box-archive"></i>
                                    <span class="fw-bold">File Attachment</span>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" id="nahkoda-tab" data-bs-toggle="tab" href="#nahkoda" aria-controls="nahkoda" role="tab" aria-selected="false">
                                    <i class="fa fa-users"></i>
                                    <span class="fw-bold">Nahkoda</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                    <div class="col-md-12">
                        <div class="tab-content">
                            @include('dashboard.pages.tugboat.components.file_attachment')
                            @include('dashboard.pages.tugboat.components.nahkoda')
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('dashboard.js')
@endpush