routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AjaxController;
use App\Http\Controllers\Dashboard\RoleController;
use App\Http\Controllers\Dashboard\UserController;
use App\Http\Controllers\Dashboard\TugboatController;
use App\Http\Controllers\Dashboard\UserLogController;
use App\Http\Controllers\Dashboard\TongkangController;
use App\Http\Controllers\Dashboard\DashboardController;
use App\Http\Controllers\Dashboard\JettyController;
use App\Http\Controllers\Dashboard\PermissionController;
use App\Http\Controllers\Perusahaan\PerusahaanController;

Auth::routes();

Route::group(["middleware" => ["auth","dashboard"]], function ()
{
    Route::get('/', [DashboardController::class, "index"])->name("dashboard.index");

    // DATATABLES
        Route::get('permission/data', [PermissionController::class, 'data'])->name('permission.data');
        Route::get('user/data', [UserController::class, 'data'])->name('user.data');
        Route::get('user-log/data', [UserLogController::class, 'data'])->name('user-log.data');
        Route::get('tugboat/data', [TugboatController::class, 'data'])->name('tugboat.data');
        Route::get('tongkang/data', [TongkangController::class, 'data'])->name('tongkang.data');
        Route::get('jetty/data', [JettyController::class, 'data'])->name('jetty.data');
    // 

    // AUTH
        Route::resource("user", UserController::class);
        Route::get("notifikasi", [UserController::class, "notifikasiIndex"])->name("notifikasi.index");
        
        Route::resource("role", RoleController::class);
        Route::get("role-add-user/{roleId}", [RoleController::class, "addUserIndex"])->name("role.add-user.index");
        Route::put("role-add-user/{roleId}", [RoleController::class, "addUserStore"])->name("role.add-user.store");
        Route::resource("permission", PermissionController::class);
        Route::resource("user-log", UserLogController::class);
        Route::post("user-log-upload/{userLogId}", [UserLogController::class, "userLogUpload"])->name("user-log.upload");
    // 

    // TUGBOAT
        Route::resource("tugboat", TugboatController::class);
        Route::post("tugboat-upload/{tugboatId}", [TugboatController::class, "upload"])->name("tugboat.upload");
        Route::get("tugboat-remove-file/{tugboatId}/{field}", [TugboatController::class, "removeFile"])->name("tugboat.remove-file");
        Route::post("tugboat-nahkoda/{tugboatId}", [TugboatController::class, "nahkodaStore"])->name("tugboat.nahkoda.store");
        Route::delete("tugboat-nahkoda/{nahkodaId}", [TugboatController::class, "nahkodaDelete"])->name("tugboat.nahkoda.delete");
    // 

    // TONGKANG
        Route::resource("tongkang", TongkangController::class);
        Route::post("tongkang-upload/{tongkangId}", [TongkangController::class, "upload"])->name("tongkang.upload");
        Route::get("tongkang-remove-file/{tongkangId}/{field}", [TongkangController::class, "removeFile"])->name("tongkang.remove-file");
    // 

    // JETTY
        Route::resource("jetty", JettyController::class);
        Route::post("jetty-upload/{jettyId}", [JettyController::class, "upload"])->name("jetty.upload");
        Route::get("jetty-remove-file/{jettyId}/{field}", [JettyController::class, "removeFile"])->name("jetty.remove-file");
    // 
    
    // PROFILE
        Route::get("profile", [UserController::class, "editProfile"])->name("profile.edit");
        Route::post("profile", [UserController::class, "updateProfile"])->name("profile.update");
    // 

    // AJAX
        Route::group(["prefix" => "ajax/", "as" => "ajax."], function ()
        {
            Route::get("mark-all-as-read", [AjaxController::class, "markAllAsRead"])->name("mark-all-as-read");
            Route::get("get-kabupaten", [AjaxController::class, "getKabupaten"])->name("get-kabupaten");
            Route::get("get-kecamatan", [AjaxController::class, "getKecamatan"])->name("get-kecamatan");
            Route::get("get-kelurahan", [AjaxController::class, "getKelurahan"])->name("get-kelurahan");
        });
    // 

    // PERUSAHAAN
        Route::group(["prefix" => "user-perusahaan/", "as" => "user-perusahaan."], function ()
        {
            Route::get("perusahaan", [PerusahaanController::class, "index"])->name("perusahaan.index");
            Route::post("perusahaan", [PerusahaanController::class, "store"])->name("perusahaan.store");
            Route::post("perusahaan-upload/{perusahaanId}", [PerusahaanController::class, "upload"])->name("perusahaan.upload");
            Route::get("perusahaan-remove-file/{perusahaanId}/{field}", [PerusahaanController::class, "removeFile"])->name("perusahaan.remove-file");
        });
    // 
});

app/Models/Role.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Spatie\Permission\Models\Role as ModelsRole;

class Role extends ModelsRole
{
    use HasFactory;

    public function roleRelation()
    {
        return $this->hasOne(RoleRelation::class);
    }
}

app/Http/Controllers/Dashboard/RoleController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Models\User;
use Illuminate\View\View;
use Illuminate\Http\Request;
use App\Http\Requests\RoleRequest;
use Illuminate\Support\Facades\DB;
use App\Http\Controllers\Controller;
use App\Repositories\Dashboard\RoleRepository;

class RoleController extends Controller
{
    protected $repository;

    public function __construct(RoleRepository $repository)
    {
        $this->title            = 'Role';
        $this->viewPath         = 'dashboard.pages.';
        $this->repository       = $repository;
        $this->modelRequest     = RoleRequest::class;
    }

    public function addUserIndex(String $id): View
    {
        $item               = $this->repository->findItem($id);

        $view               = [
            'title'                 => $this->title,
            'sub_title'             => "Role - Add User",
            'routes'                => [
                "update"                => 'role.add-user.store'
            ],
            'item'                  => $item,
            'items'                 => []
        ];

        return view("dashboard.pages.role.add_user", $view);
    }

    public function addUserStore(Request $request, $roleId)
    {
        try {
        
            DB::beginTransaction();

            $data                   = $request->all();
            $userIds                = json_decode($data["user_id"]);
            $item                   = $this->repository->findItem($roleId);

            $item->users()->detach();

            foreach ($userIds as $key => $userId) {
                $user               = User::find($userId);

                $user->syncRoles($roleId);
            }
        
            DB::commit();

            return redirect()->route("role.index")->withSuccess("Berhasil menambah user role");

        } catch (\Throwable $th) {
            DB::rollback();

            throw $th;
        }
    }
}

resources/views/dashboard/pages/role/create.blade.php
@extends('dashboard.layouts.app')

@push('dashboard.css')
<link rel="stylesheet" href="{{ asset('assets/dashboard/vendors/css/extensions/jstree.min.css') }}">
<link rel="stylesheet" href="{{ asset('assets/dashboard/css/plugins/extensions/ext-component-tree.min.css') }}">
@endpush

@section('dashboard.content')
    <div class="content-body">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header border-bottom">
                        <h4 class="card-title">{{ $sub_title }}</h4>
                    </div>
                    <div class="card-body mt-2">
                        {!! Form::open(['route' => $routes['store'], 'method' => 'POST','class' => 'form form-horizontal','enctype' => 'multipart/form-data']) !!}
                            @include($form)                            
                            <div class="row">
                                <div class="col-sm-12">
                                    <button type="submit" class="btn btn-primary me-1 float-end" onclick="SubmitForm(this, event)">Submit</button>
                                </div>
                            </div>
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('dashboard.js')
    <script src="{{ asset('assets/dashboard/vendors/js/extensions/jstree.min.js') }}"></script>
    <script>
        $(document).ready(function() {
            @foreach (collect($items["list_roles"])->chunk(3) as $key => $itemChunk)
                $("#events-{{ $key }}").jstree({
                    core: {
                        "themes" : {
                            "variant" : "large"
                        },
                        data: {!! json_encode($itemChunk->values()) !!},
                    },
                    plugins: ['types', 'checkbox', 'wholerow'],
                    types: {
                        default: { icon: 'fas fa-bolt' },
                        @foreach ($itemChunk->values() as $node)
                            {{ $node['type'] }}: { icon: '{{ $node["icon"] }}' },
                        @endforeach
                    }
                });
            @endforeach
        });

        function extractDataAndCreateJSON(selectedNodes) {
            const jsonData = [];

            selectedNodes.forEach(node => {
                if (node.original) {
                    const data = {
                        value: node.original.value,
                        parent: node.parent,
                        label: node.text,
                    };

                    jsonData.push(data);
                }
            });
            jsonAll     = jsonData;
            return jsonData;
        }

        const SubmitForm                    = (el, e) => {
            e.preventDefault();            
            var jsonData                    = [];
            @foreach (collect($items["list_roles"])->chunk(3) as $key => $itemChunk)
                var selectedNodes = $('#events-{{ $key }}').jstree("get_bottom_checked", true);
                jsonData.push(extractDataAndCreateJSON(selectedNodes));
            @endforeach

            $("input[name='permission_id']").val(JSON.stringify(jsonData));
            $(el).closest("form").submit();
        };
    </script>
@endpush

resources/views/dashboard/pages/role/edit.blade.php
@extends('dashboard.layouts.app')

@push('dashboard.css')
<link rel="stylesheet" href="{{ asset('assets/dashboard/vendors/css/extensions/jstree.min.css') }}">
<link rel="stylesheet" href="{{ asset('assets/dashboard/css/plugins/extensions/ext-component-tree.min.css') }}">
@endpush

@section('dashboard.content')
    <div class="content-body">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header border-bottom">
                        <h4 class="card-title">{{ $sub_title }}</h4>
                    </div>
                    <div class="card-body mt-2">
                        {!! Form::model($item,['route' => [$routes['update'],$item->id], 'method' => 'PUT', 'class' => 'form form-horizontal','enctype' => 'multipart/form-data']) !!}
                            @include($form)                            
                            <div class="row">
                                <div class="col-sm-12">
                                    <button type="submit" class="btn btn-primary me-1 float-end" onclick="SubmitForm(this, event)">Submit</button>
                                </div>
                            </div>
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('dashboard.js')
    <script src="{{ asset('assets/dashboard/vendors/js/extensions/jstree.min.js') }}"></script>
    <script>
        $(document).ready(function() {
            @foreach (collect($items["list_roles"])->chunk(3) as $key => $itemChunk)
                $("#events-{{ $key }}").jstree({
                    core: {
                        "themes" : {
                            "variant" : "large"
                        },
                        data: {!! json_encode($itemChunk->values()) !!},
                    },
                    plugins: ['types', 'checkbox', 'wholerow'],
                    types: {
                        default: { icon: 'fas fa-bolt' },
                        @foreach ($itemChunk->values() as $node)
                            {{ $node['type'] }}: { icon: '{{ $node["icon"] }}' },
                        @endforeach
                    }
                });
            @endforeach
        });

        function extractDataAndCreateJSON(selectedNodes) {
            const jsonData = [];

            selectedNodes.forEach(node => {
                if (node.original) {
                    const data = {
                        value: node.original.value,
                        parent: node.parent,
                        label: node.text,
                    };

                    jsonData.push(data);
                }
            });
            jsonAll     = jsonData;
            return jsonData;
        }

        const SubmitForm                    = (el, e) => {
            e.preventDefault();            
            var jsonData                    = [];
            @foreach (collect($items["list_roles"])->chunk(3) as $key => $itemChunk)
                var selectedNodes = $('#events-{{ $key }}').jstree("get_bottom_checked", true);
                jsonData.push(extractDataAndCreateJSON(selectedNodes));
            @endforeach

            $("input[name='permission_id']").val(JSON.stringify(jsonData));
            $(el).closest("form").submit();
        };
    </script>
@endpush

resources/views/dashboard/pages/role/form.blade.php
<div class="row">
    <div class="col-12 mb-2">
        <label class="form-label" for="modalRoleName">Nama</label>
        {!! Form::text('name', null, ['class' => 'form-control', 'placeholder' => 'Nama']) !!}
    </div>

    <div class="col-12 mb-2">
        <label class="form-label mb-2" for="modalRoleName">Permissions</label>
        <div class="row">
            @foreach (collect($items["list_roles"])->chunk(3) as $key => $itemChunk)
                <div class="col-4 mb-2">
                    <div class="mb-1 row">
                        <div class="col-sm-12">
                            <div id="events-{{ $key }}"></div>
                        </div>
                    </div>
                </div>
            @endforeach
            {!! Form::hidden('permission_id', null, ['class' => 'form-control', 'placeholder' => 'Events']) !!}
        </div>
    </div>
</div>

resources/views/dashboard/pages/role/form_edit.blade.php
<form id="" class="row" method="POST" action="{{ route('role.update', $item->id) }}">
    @method("PUT")
    @csrf
    <div class="col-12 mb-2">
        <label class="form-label" for="modalRoleName">Role Name</label>
        <input type="text" id="modalRoleName" name="name" class="form-control" placeholder="Enter role name" tabindex="-1" data-msg="Please enter role name" value="{{ $item->name }}" />
    </div>
    <div class="col-12 mb-2">
        <label class="form-label" for="modalRoleName">Perusahaan</label>
        {!! Form::select("perusahaan_id", $items["list_perusahaan"], $item->roleRelation->perusahaan_id ?? null, ["class" => "form-control select2 select-perusahaan", "placeholder" => "Pilih Perusahaan","onchange" => "ChangePerusahaan(this)"]) !!}
    </div>
    <div class="col-12 mb-2">
        <label class="form-label" for="modalRoleName">Departemen</label>
        {!! Form::select("departemen_id", $items["list_departemen"] ?? [], $item->roleRelation->departemen_id ?? null, ["class" => "form-control select2 select-departemen", "placeholder" => "Pilih Departemen"]) !!}
    </div>
    <div class="col-12">
        <h4 class="mt-2 pt-50">Role Permissions</h4>
        <div class="table-responsive">
            <table class="table table-flush-spacing">
                <tbody>
                    @foreach ($items["list_permission"]->chunk(4) as $permissions)
                        <tr>
                            @foreach ($permissions as $permission_id => $permission_name)
                                <td nowrap>
                                    <input class="form-check-input" type="checkbox" {{ $item->permissions->pluck("name","id")->has($permission_id) ? "checked" : "" }} id="{{ $permission_name }}" name="permission_id[]" value="{{ $permission_id }}" />
                                    <label class="form-check-label" for="{{ $permission_name }}"> {{ $permission_name }} </label>
                                </td>
                            @endforeach
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
    <div class="col-12 text-center mt-2">
        <button type="submit" class="btn btn-primary me-1">Submit</button>
        <button type="reset" class="btn btn-outline-secondary" data-bs-dismiss="modal" aria-label="Close">
            Discard
        </button>
    </div>
</form>

resources/views/dashboard/pages/role/index.blade.php
@extends('dashboard.layouts.app')

@push('dashboard.css')
    
@endpush


@section('dashboard.content')
    <div class="content-body">
        <div class="row">
            @foreach ($items["items"] as $item)
                <div class="col-xl-4 col-lg-6 col-md-6">
                    <div class="card">
                        <div class="card-body">
                            <div class="d-flex justify-content-between">
                                <span>Total {{ $item->users->count() }} users 
                                </span>
                                <ul class="list-unstyled d-flex align-items-center avatar-group mb-0">
                                    @foreach ($item->users->take(5) as $user)
                                        <li data-bs-toggle="tooltip" data-popup="tooltip-custom" data-bs-placement="top" title="{{ $user->name }}" class="avatar avatar-sm pull-up">
                                            <img class="rounded-circle" src="{{ asset('assets/dashboard/images/avatars/no_profile.png') }}" alt="Avatar" />
                                        </li>
                                    @endforeach
                                </ul>
                            </div>
                            <div class="d-flex justify-content-between align-items-end mt-1 pt-25">
                                <div class="role-heading">
                                    <h4 class="fw-bolder">{{ ucwords($item->name) }}</h4>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            @endforeach
            <div class="col-xl-4 col-lg-6 col-md-6">
                <div class="card">
                    <div class="row">
                        <div class="col-sm-5">
                            <div class="d-flex align-items-end justify-content-center h-100">
                                <img src="{{ asset('assets/dashboard/images/illustration/role-view.png') }}" class="img-fluid mt-2" alt="Image" width="85" />
                            </div>
                        </div>
                        <div class="col-sm-7">
                            <div class="card-body text-sm-end text-center ps-sm-0">
                                <a href="{{ route($routes['create']) }}" class="stretched-link text-nowrap add-new-role">
                                    <span class="btn btn-primary mb-1">Add New Role</span>
                                </a>
                                <p class="mb-0">Add role, if it does not exist</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('dashboard.js')

@endpush