routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AjaxController;
use App\Http\Controllers\Dashboard\RoleController;
use App\Http\Controllers\Dashboard\UserController;
use App\Http\Controllers\Dashboard\TugboatController;
use App\Http\Controllers\Dashboard\UserLogController;
use App\Http\Controllers\Dashboard\TongkangController;
use App\Http\Controllers\Dashboard\DashboardController;
use App\Http\Controllers\Dashboard\JettyController;
use App\Http\Controllers\Dashboard\PermissionController;
use App\Http\Controllers\Perusahaan\PerusahaanController;

Auth::routes();

Route::group(["middleware" => ["auth","dashboard"]], function ()
{
    Route::get('/', [DashboardController::class, "index"])->name("dashboard.index");

    // DATATABLES
        Route::get('permission/data', [PermissionController::class, 'data'])->name('permission.data');
        Route::get('user/data', [UserController::class, 'data'])->name('user.data');
        Route::get('user-log/data', [UserLogController::class, 'data'])->name('user-log.data');
        Route::get('tugboat/data', [TugboatController::class, 'data'])->name('tugboat.data');
        Route::get('tongkang/data', [TongkangController::class, 'data'])->name('tongkang.data');
        Route::get('jetty/data', [JettyController::class, 'data'])->name('jetty.data');
    // 

    // AUTH
        Route::resource("user", UserController::class);
        Route::get("notifikasi", [UserController::class, "notifikasiIndex"])->name("notifikasi.index");
        
        Route::resource("role", RoleController::class);
        Route::get("role-add-user/{roleId}", [RoleController::class, "addUserIndex"])->name("role.add-user.index");
        Route::put("role-add-user/{roleId}", [RoleController::class, "addUserStore"])->name("role.add-user.store");
        Route::resource("permission", PermissionController::class);
        Route::resource("user-log", UserLogController::class);
        Route::post("user-log-upload/{userLogId}", [UserLogController::class, "userLogUpload"])->name("user-log.upload");
    // 

    // TUGBOAT
        Route::resource("tugboat", TugboatController::class);
        Route::post("tugboat-upload/{tugboatId}", [TugboatController::class, "upload"])->name("tugboat.upload");
        Route::get("tugboat-remove-file/{tugboatId}/{field}", [TugboatController::class, "removeFile"])->name("tugboat.remove-file");
        Route::post("tugboat-nahkoda/{tugboatId}", [TugboatController::class, "nahkodaStore"])->name("tugboat.nahkoda.store");
        Route::delete("tugboat-nahkoda/{nahkodaId}", [TugboatController::class, "nahkodaDelete"])->name("tugboat.nahkoda.delete");
    // 

    // TONGKANG
        Route::resource("tongkang", TongkangController::class);
        Route::post("tongkang-upload/{tongkangId}", [TongkangController::class, "upload"])->name("tongkang.upload");
        Route::get("tongkang-remove-file/{tongkangId}/{field}", [TongkangController::class, "removeFile"])->name("tongkang.remove-file");
    // 

    // JETTY
        Route::resource("jetty", JettyController::class);
        Route::post("jetty-upload/{jettyId}", [JettyController::class, "upload"])->name("jetty.upload");
        Route::get("jetty-remove-file/{jettyId}/{field}", [JettyController::class, "removeFile"])->name("jetty.remove-file");
    // 
    
    // PROFILE
        Route::get("profile", [UserController::class, "editProfile"])->name("profile.edit");
        Route::post("profile", [UserController::class, "updateProfile"])->name("profile.update");
    // 

    // AJAX
        Route::group(["prefix" => "ajax/", "as" => "ajax."], function ()
        {
            Route::get("mark-all-as-read", [AjaxController::class, "markAllAsRead"])->name("mark-all-as-read");
            Route::get("get-kabupaten", [AjaxController::class, "getKabupaten"])->name("get-kabupaten");
            Route::get("get-kecamatan", [AjaxController::class, "getKecamatan"])->name("get-kecamatan");
            Route::get("get-kelurahan", [AjaxController::class, "getKelurahan"])->name("get-kelurahan");
        });
    // 

    // PERUSAHAAN
        Route::group(["prefix" => "user-perusahaan/", "as" => "user-perusahaan."], function ()
        {
            Route::get("perusahaan", [PerusahaanController::class, "index"])->name("perusahaan.index");
            Route::post("perusahaan", [PerusahaanController::class, "store"])->name("perusahaan.store");
            Route::post("perusahaan-upload/{perusahaanId}", [PerusahaanController::class, "upload"])->name("perusahaan.upload");
            Route::get("perusahaan-remove-file/{perusahaanId}/{field}", [PerusahaanController::class, "removeFile"])->name("perusahaan.remove-file");
        });
    // 
});

app/Models/Perusahaan.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Perusahaan extends Model
{
    use HasFactory, SoftDeletes;

    protected $table = "perusahaan";
    protected $fillable = [
        "nama_perusahaan",
        "nama_pemilik",
        "nib",
        "iup",
        "nib_file",
        "iup_file",
        "user_id",
    ];

    // const
    // 

    // data
    // 

    // relations
    public function user()
    {
        return $this->belongsTo(User::class, "user_id");
    }

    public function perusahaanJenis()
    {
        return $this->hasMany(PerusahaanJenis::class);
    }

    public function tugboat()
    {
        return $this->hasMany(Tugboat::class);
    }

    public function tongkang()
    {
        return $this->hasMany(Tongkang::class);
    }

    public function jetty()
    {
        return $this->hasMany(Jetty::class);
    }
    // 

    // attributes
    public function getNibFileStorageAttribute()
    {
        $str       = asset('assets/dashboard/images/noimage.png');

        if (!empty($this->nib_file)) {
            $str   = Storage::url("nib/" . $this->nib_file);
        }

        return $str;
    }

    public function getIupFileStorageAttribute()
    {
        $str       = asset('assets/dashboard/images/noimage.png');

        if (!empty($this->iup_file)) {
            $str   = Storage::url("iup/" . $this->iup_file);
        }

        return $str;
    }
    // 

    // scopes
    // 
}

app/Http/Controllers/Perusahaan/PerusahaanController.php
<?php

namespace App\Http\Controllers\Perusahaan;

use Illuminate\View\View;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Http\Controllers\Controller;
use Illuminate\Http\RedirectResponse;
use App\Repositories\Perusahaan\PerusahaanRepository;

class PerusahaanController extends Controller
{
    protected $repository;

    public function __construct(PerusahaanRepository $repository)
    {
        $this->title            = 'Perusahaan';
        $this->viewPath         = "perusahaan";
        $this->repository       = $repository;
        $this->modelRequest     = [];
    }

    public function index(): View
    {
        $view                   = [
            'title'                 => $this->title,
            'sub_title'             => "Data " . $this->title,
            'routes'                => [
                "store"                 => "user-perusahaan.perusahaan.store",
            ],
            'items'                 => $this->repository->getIndexItems(),
        ];

        return view("perusahaan.pages.perusahaan.index", $view);   
    }    

    public function store() : RedirectResponse
    {
        try {
            
            DB::beginTransaction();

            $this->repository->store(request()->all());

            DB::commit();

            return redirect()->back()->withSuccess("Berhasil merubah data");

        } catch (\Throwable $th) {
            DB::rollback();

            throw $th;
        }
    }

    public function upload(Request $request, $perusahaanId)
    {
        try {
            
            DB::beginTransaction();

            $items      = $this->repository->upload(request()->all(), $perusahaanId);

            DB::commit();

            return response()->json(makeResponse(true, 'success', [
                "view"          => view("components.files.after_upload", $items)->render(),
                "parent_div"    => request()->field,
            ]));

        } catch (\Throwable $th) {
            DB::rollback();

            throw $th;
        }
    }

    public function removeFile(Request $request, $perusahaanId, $jenisFile)
    {
        try {
            
            DB::beginTransaction();

            $this->repository->removeFile(request()->all(), $perusahaanId, $jenisFile);

            DB::commit();

            return redirect()->back()->withSuccess("Berhasil menghapus file");

        } catch (\Throwable $th) {
            DB::rollback();

            throw $th;
        }
    }
}

resources/views/perusahaan/pages/perusahaan/file_attachment.blade.php
<div class="row">
    @if (empty(auth()->user()->perusahaan))
        <div class="alert alert-danger" role="alert">
            <div class="alert-body">
                <i data-feather="info" class="me-50"></i>
                <span>Harap Lengkapi Data Perusahaan Terlebih Dahulu</span>
            </div>
        </div>
    @else
        @foreach ($items["list_files"] as $listFiles)
            <div class="col-md-4" id="{{ $listFiles["name"] }}">
                @if (!empty(auth()->user()->perusahaan) && !empty(auth()->user()->perusahaan->{$listFiles["name"]}))
                    @include('components.files.after_upload', ["fileUrl" => auth()->user()->perusahaan->{$listFiles["name"] . "_storage"}, "fileName" => $listFiles["label"], "removeFileUrl" => route("user-perusahaan.perusahaan.remove-file", [auth()->user()->perusahaan->id, $listFiles["name"]]), ""])
                @else
                    @include("components.files.before_upload", ["fileName" => $listFiles["label"], "fileField" => $listFiles["name"], "uploadUrl" => route("user-perusahaan.perusahaan.upload", auth()->user()->perusahaan->id)])
                @endif
            </div>
        @endforeach
    @endif
</div>

resources/views/perusahaan/pages/perusahaan/form.blade.php
{!! Form::open(['route' => $routes['store'], 'method' => 'POST','class' => 'form form-horizontal','enctype' => 'multipart/form-data']) !!}
                        
    <div class="row">
        <div class="col-12">
            <div class="mb-1 row">
                <div class="col-sm-3">
                    <label class="col-form-label">Nama Perusahaan</label>
                </div>
                <div class="col-sm-9">
                    {!! Form::text('nama_perusahaan', auth()->user()->perusahaan->nama_perusahaan ?? "", ['class' => 'form-control', 'placeholder' => 'Nama Perusahaan']) !!}
                </div>
            </div>
        </div>
        <div class="col-12">
            <div class="mb-1 row">
                <div class="col-sm-3">
                    <label class="col-form-label">Nama Pemilik</label>
                </div>
                <div class="col-sm-9">
                    {!! Form::text('nama_pemilik', auth()->user()->perusahaan->nama_pemilik ?? "", ['class' => 'form-control', 'placeholder' => 'Nama Pemilik']) !!}
                </div>
            </div>
        </div>
        <div class="col-12">
            <div class="mb-1 row">
                <div class="col-sm-3">
                    <label class="col-form-label">NIB</label>
                </div>
                <div class="col-sm-9">
                    {!! Form::number('nib', auth()->user()->perusahaan->nib ?? "", ['class' => 'form-control', 'placeholder' => 'NIB']) !!}
                </div>
            </div>
        </div>
        <div class="col-12">
            <div class="mb-1 row">
                <div class="col-sm-3">
                    <label class="col-form-label">IUP</label>
                </div>
                <div class="col-sm-9">
                    {!! Form::text('iup', auth()->user()->perusahaan->iup ?? "", ['class' => 'form-control', 'placeholder' => 'IUP']) !!}
                </div>
            </div>
        </div>
        <div class="col-12">
            <div class="mb-1 row">
                <div class="col-sm-3">
                    <label class="col-form-label">Jenis</label>
                </div>
                <div class="col-sm-9">
                    {!! Form::select('jenis[]', $items["list_jenis"] ?? [], !empty(auth()->user()->perusahaan) && auth()->user()->perusahaan->perusahaanJenis->isNotEmpty() ? auth()->user()->perusahaan->perusahaanJenis->pluck("jenis") : [], ['class' => 'form-control select2', 'multiple']) !!}
                </div>
            </div>
        </div>
    </div>
    
    <div class="row">
        <div class="col-sm-9 offset-sm-3">
            <button type="submit" class="btn btn-primary me-1">Submit</button>
        </div>
    </div>
{!! Form::close() !!}

resources/views/perusahaan/pages/perusahaan/index.blade.php
@extends('dashboard.layouts.app')

@push('dashboard.css')
    
@endpush


@section('dashboard.content')
    <div class="content-body">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-header border-bottom">
                        <h4 class="card-title">{{ $sub_title }}</h4>
                    </div>
                    <div class="card-body mt-2 pb-2">
                        @include('perusahaan.pages.perusahaan.form')
                    </div>
                </div>
            </div>

            <div class="col-6">
                <div class="card">
                    <div class="card-header border-bottom">
                        <h4 class="card-title">File Attachment</h4>
                    </div>
                    <div class="card-body mt-2 pb-2">
                        @include('perusahaan.pages.perusahaan.file_attachment')
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('dashboard.js')
@endpush